In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3])

In [3]:
A.dtype

dtype('int32')

In [4]:
A.size

3

In [5]:
A.ndim

1

In [6]:
A.shape

(3,)

In [11]:
# random
np.random.seed(0) 
np.random.randn(3, 4) #randn() is the most used in data science & ML

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
# np.linspace(start, end, quantity)
# np.arabge(start,end, step)

## useful for matplotlib !

In [16]:
# linspace()
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [19]:
# linspace()
np.linspace(0, 10, 20, dtype=np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

In [15]:
# arange()
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

# manipulation

In [20]:
A = np.zeros((3,2))
B = np.ones((3,2))

In [21]:
A

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
# hstack() vs vstack
# np.hstack((ArrayA, ArrayB))

In [28]:
# hstack()
C = np.hstack((A, B))
C

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [29]:
C.shape

(3, 4)

In [26]:
# vstack()
D = np.vstack((A, B))
D

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
D.shape

(6, 2)

In [32]:
# np.concatenate((ArrayA, ArrayB), axis=1 or 0)
np.concatenate((A, B), axis=1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [31]:
np.concatenate((A, B), axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
# recommend focus on concatenate

In [34]:
# reshape()
D.reshape((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
D.shape

(6, 2)

In [36]:
A = np.array([1,2,4])

In [37]:
A.shape

(3,)

In [39]:
A = A.reshape((A.shape[0], 1))
A.shape

(3, 1)

In [40]:
# returning back to original shape (3,)
A= A.squeeze()
A.shape

(3,)

In [43]:
# ravel()
D.ravel()

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])